import {
  Anchor,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bed,
  Bird,
  Car,
  Check,
  Clock,
  Coffee,
  Compass,
  Dog,
  Fan,
  Fish,
  Flame,
  Footprints,
  Leaf,
  Mail,
  MapPin,
  Maximize,
  Moon,
  Phone,
  Plane,
  Quote,
  Sailboat,
  Ship,
  Sparkles,
  Star,
  Sunrise,
  Train,
  UtensilsCrossed,
  Users,
  Waves,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";

/**
 * Data files name an icon as a string; this map turns it into a component, so
 * a typo in a data file is a compile error rather than a blank space.
 */
export const icons = {
  anchor: Anchor,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  bed: Bed,
  bird: Bird,
  car: Car,
  check: Check,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  dog: Dog,
  fan: Fan,
  fish: Fish,
  flame: Flame,
  footprints: Footprints,
  leaf: Leaf,
  mail: Mail,
  mapPin: MapPin,
  maximize: Maximize,
  moon: Moon,
  phone: Phone,
  plane: Plane,
  quote: Quote,
  sailboat: Sailboat,
  ship: Ship,
  sparkles: Sparkles,
  star: Star,
  sunrise: Sunrise,
  train: Train,
  utensils: UtensilsCrossed,
  users: Users,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
