import {
  Accessibility,
  Activity,
  ArrowRight,
  ArrowUpRight,
  Baby,
  Bone,
  Brain,
  Building,
  CalendarCheck,
  CalendarDays,
  Car,
  Check,
  ClipboardList,
  Clock,
  CreditCard,
  Ear,
  Eye,
  HandHeart,
  HeartPulse,
  Languages,
  Mail,
  MapPin,
  Microscope,
  Phone,
  Search,
  ShieldCheck,
  Toothbrush,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  TrainFront,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Data files name an icon as a string; this map turns it into a component, so
 * a typo in a data file is a compile error rather than a blank space.
 */
export const icons = {
  accessibility: Accessibility,
  activity: Activity,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  baby: Baby,
  bone: Bone,
  brain: Brain,
  building: Building,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  car: Car,
  check: Check,
  clipboard: ClipboardList,
  clock: Clock,
  creditCard: CreditCard,
  ear: Ear,
  eye: Eye,
  handHeart: HandHeart,
  heartPulse: HeartPulse,
  languages: Languages,
  mail: Mail,
  mapPin: MapPin,
  microscope: Microscope,
  phone: Phone,
  search: Search,
  shieldCheck: ShieldCheck,
  smile: Toothbrush,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  syringe: Syringe,
  train: TrainFront,
  users: Users,
  wallet: Wallet,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
