import {
  Accessibility,
  Activity,
  ArrowRight,
  ArrowUpRight,
  Award,
  Baby,
  Bone,
  Brush,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  Clock,
  Cpu,
  Drill,
  Droplets,
  GraduationCap,
  HeartHandshake,
  Languages,
  Layers,
  Mail,
  MapPin,
  Microscope,
  Monitor,
  Navigation,
  Phone,
  ScanLine,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Users,
  Wind,
  type LucideIcon,
} from "lucide-react";

/**
 * Data files name an icon as a string; this map turns it into a component.
 * Deriving the union from the map means a typo in a data file is a compile
 * error rather than a blank space on the page.
 */
export const icons = {
  accessibility: Accessibility,
  activity: Activity,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  award: Award,
  baby: Baby,
  bone: Bone,
  brush: Brush,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  camera: Camera,
  car: Car,
  check: Check,
  clock: Clock,
  cpu: Cpu,
  drill: Drill,
  droplets: Droplets,
  graduationCap: GraduationCap,
  heartHandshake: HeartHandshake,
  languages: Languages,
  layers: Layers,
  mail: Mail,
  mapPin: MapPin,
  microscope: Microscope,
  monitor: Monitor,
  navigation: Navigation,
  phone: Phone,
  scanLine: ScanLine,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  syringe: Syringe,
  users: Users,
  wind: Wind,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
