import {
  ArrowRight,
  ArrowUpRight,
  Bed,
  Calendar,
  CalendarDays,
  Bike,
  Camera,
  Car,
  CloudRain,
  Croissant,
  Clock,
  Coffee,
  Compass,
  Dog,
  Eye,
  Flame,
  Footprints,
  Heart,
  Leaf,
  Mail,
  MapPin,
  Maximize,
  Moon,
  Mountain,
  MountainSnow,
  Navigation,
  Phone,
  Sparkles,
  Star,
  Snowflake,
  Soup,
  Sun,
  Sunrise,
  Tent,
  Trees,
  Users,
  Utensils,
  Wifi,
  type LucideIcon,
} from "lucide-react";

/**
 * Data files name an icon as a string; this map turns it into a component, so
 * a typo in a data file is a compile error rather than a blank space.
 */
export const icons = {
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  bed: Bed,
  calendar: Calendar,
  calendarDays: CalendarDays,
  bike: Bike,
  camera: Camera,
  car: Car,
  cloudRain: CloudRain,
  croissant: Croissant,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  dog: Dog,
  eye: Eye,
  flame: Flame,
  footprints: Footprints,
  heart: Heart,
  leaf: Leaf,
  mail: Mail,
  mapPin: MapPin,
  maximize: Maximize,
  moon: Moon,
  mountain: Mountain,
  mountainSnow: MountainSnow,
  navigation: Navigation,
  phone: Phone,
  sparkles: Sparkles,
  star: Star,
  snowflake: Snowflake,
  soup: Soup,
  sun: Sun,
  sunrise: Sunrise,
  tent: Tent,
  trees: Trees,
  users: Users,
  utensils: Utensils,
  wifi: Wifi,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
