/**
 * Bakes the project list into the dashboard: dashboard/src/generated/projects.json.
 *
 * The dashboard is a static export, so it cannot read the filesystem at run
 * time — this file is its only source of truth about what exists. It is
 * committed, so `cd dashboard && npm run dev` works on a fresh clone, and
 * regenerated by tools/build.mjs before every dashboard build.
 *
 *   node tools/manifest.mjs            write it
 *   node tools/manifest.mjs --check    fail if it is out of date
 */
import fs from 'node:fs';
import path from 'node:path';
import { MANIFEST_FILE, TITLE, TAGLINE, ROOT } from './config.mjs';
import { listCategories } from './projects.mjs';

/** Absolute paths must never reach a published page. */
const publicFields = ({ dir, ...rest }) => rest;

export function buildManifest() {
  return {
    title: TITLE,
    tagline: TAGLINE,
    categories: listCategories().map((category) => ({
      ...category,
      projects: category.projects.map(publicFields),
    })),
  };
}

const serialize = (manifest) => `${JSON.stringify(manifest, null, 2)}\n`;

export function writeManifest() {
  const text = serialize(buildManifest());
  fs.mkdirSync(path.dirname(MANIFEST_FILE), { recursive: true });
  const current = fs.existsSync(MANIFEST_FILE) ? fs.readFileSync(MANIFEST_FILE, 'utf8') : null;
  if (current === text) return false;
  fs.writeFileSync(MANIFEST_FILE, text);
  return true;
}

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('manifest.mjs')) {
  const rel = path.relative(ROOT, MANIFEST_FILE).split(path.sep).join('/');
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(MANIFEST_FILE) ? fs.readFileSync(MANIFEST_FILE, 'utf8') : '';
    if (current !== serialize(buildManifest())) {
      console.error(`${rel} is out of date — run: npm run manifest`);
      process.exit(1);
    }
    console.log(`${rel} is up to date.`);
  } else {
    console.log(writeManifest() ? `wrote ${rel}` : `${rel} was already up to date`);
  }
}
